services:
  app-db:
    image: mysql:8
    command:
      --collation-server=utf8mb4_0900_bin
      --transaction-isolation=READ-COMMITTED
    restart: always
    container_name: app-db
    hostname: app-db
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 53306:3306
  app-frontend:
    build: ./dev/app/frontend
    container_name: app-frontend
    hostname: app-frontend
    volumes:
      - $PWD/dev/app/frontend:/app
      - $PWD/dev/app/frontend/node_modules:/app/node_modules
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    stdin_open: true
  app-backend:
    build: ./dev/app/backend
    container_name: app-backend
    hostname: app-backend
    volumes:
      - $PWD/dev/app/backend:/go/src/app
    ports:
      - 4000:4000
    stdin_open: true