services:
  app-db:
    image: mysql:8
    command:
      --collation-server=utf8mb4_0900_bin
      --transaction-isolation=READ-COMMITTED
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 53306:3306
  app-frontend:
    build: ./dev/app/frontend
    container_name: app-frontend
    hostname: app-frontend
    volumes:
      - $PWD/dev/app/frontend:/app
      - $PWD/dev/app/frontend/node_modules:/app/node_modules
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    command: sh -c "npm run dev"
    stdin_open: true